broker:
    timeout: 3
    max_conn: Default
    max_tries: 5
    judges: Default
    providers: Default
    verify_ssl: Default

serve:
    host: 0.0.0.0
    port: 8888
    limit: 10
    max_tries: 10
    min_req_proxy: 5
    max_error_rate: 0.5
    max_resp_time: 8
    prefer_connect: True
    http_allowed_codes:
        - 200
        - 301
        - 302
    countries: Default
    post: Default
    strict: True
    dnsbl: Default
    backlog: Default
    check: True
    types: Default # Change this directly inside broker.py.
